### ISSUE TITLE
Access denied: channel [] creator org unknown, creator is malformed)

### ISSUE THREAD

**Issue by DavidCasalod** [kctam/4host-swarm#2]
when I run the mychannelup.sh script, only host 1 joins. I get this error in host 2:

Logs peer0.org1:

2023-07-10 10:22:50.718 UTC [core.comm] ServerHandshake -> ERRO 091 Server TLS handshake failed in 2.660529ms with error remote error: tls: bad certificate server=PeerServer remoteaddress=10.0.2.213:42642
2023-07-10 10:22:52.917 UTC [gossip.comm] authenticateRemotePeer -> WARN 092 Identity store rejected 10.0.2.213:9051 : failed classifying identity: Unable to extract msp.Identity from peer Identity: Peer Identity {"CN":"peer0.org1.example.com","Issuer-CN":"ca.org1.example.com","Issuer-L-ST-C":"[San Francisco]-[]-[US]","Issuer-OU":["COP"],"L-ST-C":"[San Francisco]-[]-[US]","MSP":"Org2MSP","OU":["COP"]} cannot be validated. No MSP found able to do that.

Logs orderer:
2023-07-10 10:20:35.420 UTC [common.deliver] deliverBlocks -> WARN 05c [channel: mychannel] Rejecting deliver request for 10.0.2.209:55046 because of consenter error

logs peer0.org2:

2023-07-10 10:33:35.257 UTC 0159 WARN [gossip.discovery] func1 -> Could not connect to Endpoint: peer0.org1.example.com:7051, InternalEndpoint: peer0.org1.example.com:7051, PKI-ID: <nil>, Metadata:  : context deadline exceeded
2023-07-10 10:33:43.340 UTC 015a INFO [comm.grpc.server] 1 -> unary call completed grpc.service=gossip.Gossip grpc.method=Ping grpc.request_deadline=2023-07-10T10:33:45.339Z grpc.peer_address=10.0.2.208:45552 grpc.peer_subject="CN=peer0.org1.example.com,L=San Francisco,ST=California,C=US" grpc.code=OK grpc.call_duration=158.375µs
2023-07-10 10:33:43.343 UTC 015b WARN [gossip.comm] authenticateRemotePeer -> Identity store rejected 10.0.2.208:45552 : failed classifying identity: Unable to extract msp.Identity from peer Identity: Peer Identity {"CN":"peer0.org1.example.com","Issuer-CN":"ca.org1.example.com","Issuer-L-ST-C":"[San Francisco]-[]-[US]","Issuer-OU":null,"L-ST-C":"[San Francisco]-[]-[US]","MSP":"Org1MSP","OU":["peer"]} cannot be validated. No MSP found able to do that.
2023-07-10 10:33:43.343 UTC 015c ERRO [gossip.comm] GossipStream -> Authentication failed: failed classifying identity: Unable to extract msp.Identity from peer Identity: Peer Identity {"CN":"peer0.org1.example.com","Issuer-CN":"ca.org1.example.com","Issuer-L-ST-C":"[San Francisco]-[]-[US]","Issuer-OU":null,"L-ST-C":"[San Francisco]-[]-[US]","MSP":"Org1MSP","OU":["peer"]} cannot be validated. No MSP found able to do that.
2023-07-10 10:33:43.343 UTC 015d INFO [comm.grpc.server] 1 -> streaming call completed grpc.service=gossip.Gossip grpc.method=GossipStream grpc.request_deadline=2023-07-10T10:33:53.341Z grpc.peer_address=10.0.2.208:45552 grpc.peer_subject="CN=peer0.org1.example.com,L=San Francisco,ST=California,C=US" error="failed classifying identity: Unable to extract msp.Identity from peer Identity: Peer Identity {\"CN\":\"peer0.org1.example.com\",\"Issuer-CN\":\"ca.org1.example.com\",\"Issuer-L-ST-C\":\"[San Francisco]-[]-[US]\",\"Issuer-OU\":null,\"L-ST-C\":\"[San Francisco]-[]-[US]\",\"MSP\":\"Org1MSP\",\"OU\":[\"peer\"]} cannot be validated. No MSP found able to do that." grpc.code=Unknown grpc.call_duration=1.453263ms

**Comment by dkanavaris** [comment]
Hello, 
Did you manage to find any solution to this ?
I have the same problem.

**Comment by dc-atos-dev** [comment]
Hi I'm David again,
No, I'm still stuck with TLS issues.
Have you managed to make any progress? Any help would be appreciated,
thank you!

**Comment by dkanavaris** [comment]
In host 1 issue the following command :
docker execl cli peer version 
If the version is 2.5.3 (latest) then in the hostn.yaml files add this
```- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp```
as an environment variable to each peer.
Alternatively when spinning up the containers try to use the 2.4.9 image instead of latest (replace latest with 2.4.9).
Both of the solutions worked for me but went with the first since it uses the latest version

**Comment by dc-atos-dev** [comment]
Hi thanks for the info.

Should I modify also this in the host1.yaml?

- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp

And Should I add it as an enviroment variable inside of the peers?? 
because I only have one cli container in the host1 and I don't have it in the rest of the hostn.yaml.

Do you have your code in a public repo?

**Comment by dkanavaris** [comment]
``` - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp ``` should be added in each peer not the cli in the enviroment variables. My code is not in a public repo but here is a snipper of how each peer should be configured
```
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - byfn
  ``` 

Notice the that ``` - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp ``` is added in the peers enviroments. That should be done for each peer even if the peer belongs to a different host
